version: '2'
services:
  elasticsearch:
    image: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      
  gems:
    image: busybox
    volumes:
      - /gems
  
  source_code:
    image: busybox
    volumes:
      - .:/forum-api
      
  app:
    build: .
    command: bin/docker-start
    env_file: .env
    links:
      - db
      - elasticsearch
    volumes_from:
      - gems
      - source_code
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch

volumes:
  elasticsearch: {}
  postgres: {}
